# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - arvwebapp-dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy-dev:
    runs-on: windows-latest
    needs: build
    environment: dev
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F3F52AC085AB4DE98BD7FCDD27F1473F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0A472152A34B45BA80BD0247078A83DD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7B1844C14CBF49CBB4E5D9934B0A30AD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'arvwebapp-dev'
          slot-name: 'Production'
          package: .

  deploy-staging:
    runs-on: windows-latest
    needs: deploy-dev
    environment: 
      name: staging
      url: https://arvwebapp-staging-fndqakfaceesftcz.westus-01.azurewebsites.net/
      
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F3F52AC085AB4DE98BD7FCDD27F1473F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0A472152A34B45BA80BD0247078A83DD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7B1844C14CBF49CBB4E5D9934B0A30AD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'arvwebapp'
          slot-name: 'staging'
          package: .
  deploy-PROD:
    runs-on: windows-latest
    needs: deploy-staging
    environment: 
      name: PROD
      url: https://arvwebapp-a6f4djfreag7ghb0.westus-01.azurewebsites.net/
      
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F3F52AC085AB4DE98BD7FCDD27F1473F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0A472152A34B45BA80BD0247078A83DD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7B1844C14CBF49CBB4E5D9934B0A30AD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'arvwebapp'
          slot-name: 'production'
          package: .
